version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: todo_db
      JWT_SECRET: mysecret
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: